baseurl: ''
permalink: pretty
title: 'Nathan Winter & Associates'
show_title: false
email: 'webmaster@arcana.com.au'
description: 'Management Consultants that specialise in providing Governance, Risk Management, Occupational Health & Safety, Quality & Environmental Advisory and Assurance Services.'
services_style: detailed # possible values: detailed, short
intro_background_image: "images/header-bg.jpg"

# url: "https://nwassociates.com.au" # the base hostname & protocol for your site, e.g. http://example.com

homepage:
  show_call_box: true

footer:
  copyright_text: '© Copyright Nathan Winter & Associates 2025 – All rights reserved.'

seo:
  meta_og_title: "Nathan Winter & Associates"
  meta_og_type: "website"
  meta_og_url: "https://nwassociates.com.au"
  meta_og_image: "https://nwassociates.com.au/images/social.png"
  meta_og_description: "Management Consultants that specialise in providing Governance, Risk Management, Occupational Health & Safety, Quality & Environmental Advisory and Assurance Services."
  google_analytics_id: ""

logo:
  mobile: "images/logo/logo.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "50px"

home: 
  limit_services: 20

services: 
  limit_services: 20

collections:
  services:
    output: true
  team:
    output: true
  products:
    output: true
  news:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

url: "https://nwassociates.com.au"

plugins:
  - jekyll-environment-variables
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md

